project:
  type: website
  output-dir: docs

website:
  title: "Matthew Tan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: fyp.qmd
        text: FYP Project
      - href: hackathons.qmd
        text: Hackathons
      - href: data-visualization.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: GenAI Reflection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true